import type { VisaScoreResult } from "./visa-score";

export function generateVisaScorecardCanvas(
  result: VisaScoreResult,
  studentName: string,
  canvas: HTMLCanvasElement,
): void {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  const w = canvas.width;
  const h = canvas.height;
  const score = result.score;

  const color = score >= 70 ? "#16a34a" : score >= 40 ? "#ca8a04" : "#dc2626";
  const label = score >= 70 ? "High Chance" : score >= 40 ? "Moderate Chance" : "Low Chance";
  const emoji = score >= 70 ? "🚀" : score >= 40 ? "👍" : "⚠️";

  // Background
  const bg = ctx.createLinearGradient(0, 0, 0, h);
  bg.addColorStop(0, "#0f172a");
  bg.addColorStop(1, "#1e293b");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, w, h);

  // Top bar accent
  ctx.fillStyle = color;
  ctx.fillRect(0, 0, w, 6);

  // Brand
  ctx.fillStyle = "#14b8a6";
  ctx.font = "bold 36px sans-serif";
  ctx.fillText("Probash Academic", 40, 60);

  ctx.fillStyle = "#64748b";
  ctx.font = "20px sans-serif";
  ctx.fillText("AI Visa Eligibility Scorecard", 40, 90);

  // Score circle
  const cx = 200;
  const cy = 340;
  const rad = 100;
  const circum = 2 * Math.PI * rad;

  // Background circle
  ctx.beginPath();
  ctx.arc(cx, cy, rad, 0, Math.PI * 2);
  ctx.strokeStyle = "#334155";
  ctx.lineWidth = 14;
  ctx.stroke();

  // Score arc (counter-clockwise from top)
  const fraction = score / 100;
  ctx.beginPath();
  ctx.arc(cx, cy, rad, -Math.PI / 2, -Math.PI / 2 + fraction * Math.PI * 2);
  ctx.strokeStyle = color;
  ctx.lineWidth = 14;
  ctx.lineCap = "round";
  ctx.stroke();

  // Score text
  ctx.fillStyle = "#ffffff";
  ctx.font = "bold 64px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText(String(score), cx, cy - 10);

  ctx.fillStyle = color;
  ctx.font = "bold 24px sans-serif";
  ctx.fillText(label, cx, cy + 36);

  ctx.fillStyle = "#94a3b8";
  ctx.font = "36px sans-serif";
  ctx.fillText(emoji, cx, cy + 80);

  // Right side: factor breakdown
  const factorsX = 390;
  const factorY = 200;
  const factorLabels = [
    { key: "academicProfile", label: "Academic Profile" },
    { key: "languageProficiency", label: "Language" },
    { key: "financialReadiness", label: "Financial" },
    { key: "destinationMatch", label: "Destination Match" },
    { key: "immigrationRisk", label: "Immigration Risk" },
  ];

  ctx.textAlign = "left";
  factorLabels.forEach((f, i) => {
    const y = factorY + i * 55;
    const val = result.factors[f.key as keyof typeof result.factors];
    const frac = val / 100;

    ctx.fillStyle = "#94a3b8";
    ctx.font = "16px sans-serif";
    ctx.fillText(f.label, factorsX, y);

    // Bar background
    ctx.fillStyle = "#334155";
    ctx.fillRect(factorsX, y + 6, 300, 10);

    // Bar fill
    const barColor = val >= 70 ? "#16a34a" : val >= 40 ? "#ca8a04" : "#dc2626";
    ctx.fillStyle = barColor;
    ctx.fillRect(factorsX, y + 6, Math.max(4, 300 * frac), 10);

    // Value
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 16px sans-serif";
    ctx.textAlign = "right";
    ctx.fillText(`${val}/100`, factorsX + 320, y);
    ctx.textAlign = "left";
  });

  // Bottom: recommendations
  const recY = 520;
  ctx.fillStyle = "#14b8a6";
  ctx.font = "bold 18px sans-serif";
  ctx.fillText("Recommendations", 40, recY);

  if (result.recommendations.length > 0) {
    result.recommendations.slice(0, 2).forEach((rec, i) => {
      ctx.fillStyle = "#cbd5e1";
      ctx.font = "16px sans-serif";
      ctx.fillText(`→ ${rec}`, 40, recY + 30 + i * 28);
    });
  }

  // Footer
  ctx.fillStyle = "#475569";
  ctx.font = "14px sans-serif";
  ctx.textAlign = "center";
  ctx.fillText("Generated by Probash Academic — AI-powered study abroad platform", w / 2, h - 30);
  ctx.textAlign = "left";
}
